### ISSUE TITLE
Support --cli-input-json

### ISSUE THREAD

**Issue by alanivey** [widdix/cfn-create-or-update#1]
I'm currently parsing AWS CLI output to ignore _No updates are to be performed_ from the error output while failing on anything else. It's a hack, so `cfn-create-or-update` is very welcome. I made a "universal" updating script to keep Parameters and Capabilities the same for when I'm only updating the template. It currently works something like this:

```bash
# A previous step uploads template file to $S3CfnSource ...

CFN_STACK_JSON="$( aws --region "${REGION:?}" cloudformation describe-stacks --stack-name "${CFN_STACK:?}" | jq -M '.Stacks[0] | {Parameters:.Parameters,Capabilities:.Capabilities} | del(.Parameters[].ParameterValue) | .Parameters[] |= .+ {UsePreviousValue: true}' )"

aws --region "${REGION:?}" \
    cloudformation \
    update-stack \
    --stack-name "${CFN_STACK:?}" \
    --template-url "https://s3.amazonaws.com/${S3CfnSource:?}/${CFN_SOURCE:?}" \
    --cli-input-json "${CFN_STACK_JSON:?}"
```

Because it's possible to have a stack without parameters or capabilities, I can use `--cli-input-json` to pass when I do have values and the input will be valid even when the JSON does not contain values for those items. If you could include support for `--cli-input-json`, I would be able to drop your script in place and remove the nonsense I currently use to parse the error output. Thanks!

**Comment by michaelwittig** [comment]
This project is no longer maintained.
