### ISSUE TITLE
npm audit results in '3 vulnerabilities require manual review'

### ISSUE THREAD

**Issue by mblpz** [widdix/cfn-create-or-update#10]
through to exactly pinned dependency versions in the _package.json_ _npm_ audit fix can't do its work for sub-dependent security vulnerabilities in **_proxy-agent_**.

could you please change the way you require dependent packages to ^, ~ or *?

**Comment by mblpz** [comment]
#11

**Comment by michaelwittig** [comment]
Thanks for bringing this to my attention. Fixed in #12 

Released as `cfn-create-or-update@1.4.0`
