### ISSUE TITLE
Parameter --wait does not work

### ISSUE THREAD

**Issue by froehr** [widdix/cfn-create-or-update#2]
Hey,
great work until now but I found that the wait parameter does not work as its ignored in `cli.js`. This is probably due to a missing assignment in the `cli.js`.

Adding:
```
if (has('wait')) {
  args.wait = string('wait');
}
```
In line 125 of `cli.js` will probably solve the issue.

Thanks

**Comment by michaelwittig** [comment]
Thanks @froehr 
I released v1.1.2 which includes the fix.
