### ISSUE TITLE
CloudFormation stack is not deleted when creation fails

### ISSUE THREAD

**Issue by michaelwittig** [widdix/cfn-create-or-update#3]
After a CloudFormation stack fails to create, it can no longer be used but is not deleted by the plugin. This causes all future updates to fail with a "<stack name> is in ROLLBACK_COMPLETE state and can not be updated." error.

**Comment by romaninsh** [comment]
I think it is better this way, it's very useful to see stack with the error for debugging. The script, however, should properly recognize this state and perform a DELETE when it's invoked next time.

**Comment by michaelwittig** [comment]
This project is no longer maintained.
