### ISSUE TITLE
Concurrent Create/Updates are throttled causing non-zero exit code

### ISSUE THREAD

**Issue by mcblair** [widdix/cfn-create-or-update#6]
Experiencing this issue when I'm running multiple create or updates concurrently.

`Resource is not in the state stackUpdateComplete Throttling: Resource is not in the state stackUpdateComplete at Request.extractError (/usr/lib/node_modules/cfn-create-or-update/node_modules/aws-sdk/lib/protocol/query.js:47:29) at Request.callListeners (/usr/lib/node_modules/cfn-create-or-update/node_modules/aws-sdk/lib/sequential_executor.js:105:20) at Request.emit (/usr/lib/node_modules/cfn-create-or-update/node_modules/aws-sdk/lib/sequential_executor.js:77:10) at Request.emit (/usr/lib/node_modules/cfn-create-or-update/node_modules/aws-sdk/lib/request.js:673:14) at Request.transition (/usr/lib/node_modules/cfn-create-or-update/node_modules/aws-sdk/lib/request.js:22:10) at AcceptorStateMachine.runTo (/usr/lib/node_modules/cfn-create-or-update/node_modules/aws-sdk/lib/state_machine.js:14:12) at /usr/lib/node_modules/cfn-create-or-update/node_modules/aws-sdk/lib/state_machine.js:26:10 at Request.<anonymous> (/usr/lib/node_modules/cfn-create-or-update/node_modules/aws-sdk/lib/request.js:38:9) at Request.<anonymous> (/usr/lib/node_modules/cfn-create-or-update/node_modules/aws-sdk/lib/request.js:675:12) at Request.callListeners (/usr/lib/node_modules/cfn-create-or-update/node_modules/aws-sdk/lib/sequential_executor.js:115:18)`

The reality is, the cloudformation stack was created/updated successfully - but due to the CLI exiting non-zero, our pipeline task fails.

**Comment by mcblair** [comment]
Through further research, it appears this might be limited per account. A request for an increase for cloudformation API requests seems to be in order.

**Comment by michaelwittig** [comment]
Hi @mcblair the reason for this is that a CloudFormation update takes some time. During this time, the tool pools the state to check if the updated completed or failed

 Implementation is done with http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudFormation.html#stackUpdateComplete-waiter
Unfortunately, the poll interval does not seem to be adjustable...

So increasing API limits helps or we have to implement the waitFor part on our own...

**Comment by mcblair** [comment]
Thanks @michaelwittig
