### ISSUE TITLE
Issue passing string array parameters 

### ISSUE THREAD

**Issue by rajeshgopal** [widdix/cfn-create-or-update#8]
`sudo /usr/bin/cfn-create-or-update --stack-name sample --template-body file://Tomcat-app-cfn.yaml --region us-east-1 --parameters ParameterKey=KeyName,ParameterValue=rg-newkey ParameterKey=AppURL,ParameterValue=http://localhost/app.war ParameterKey=VPCId,ParameterValue=vpc-12345 ParameterKey=EC2Subnets,ParameterValue="subnet-123456,subnet-789109"
`
When I run this command it throws error _parameters[3] ParameterKey, ParameterValue or UsePreviousValue expected
_ for EC2Subnets Parameter. whereas the aws cloudformation create-stack command works with same value.

Please let me know what's the right syntax to pass array or list parameter values.

**Comment by michaelwittig** [comment]
Can you try this:

```
sudo /usr/bin/cfn-create-or-update --stack-name sample --template-body file://Tomcat-app-cfn.yaml --region us-east-1 --parameters "ParameterKey=KeyName,ParameterValue=rg-newkey" "ParameterKey=AppURL,ParameterValue=http://localhost/app.war" "ParameterKey=VPCId,ParameterValue=vpc-12345" "ParameterKey=EC2Subnets,ParameterValue=subnet-123456,subnet-789109"
```

**Comment by rajeshgopal** [comment]
Still getting same error
```
[ec2-user@ip-172-31-72-163 aws]$ sudo /usr/bin/cfn-create-or-update --stack-name sample-tomcat-app --region us-east-1 --template-body file://Tomcat-app-cfn.yaml --parameters "ParameterKey=KeyName,ParameterValue=rg-newkey" "ParameterKey=AppURL,ParameterValue=http://172.31.70.8:8081/artifactory/maven-snapshot-local/test/springboot-sample-app/0.0.1-SNAPSHOT/springboot-sample-app-0.0.1-20180228.053020-1.war" "ParameterKey=VPCId,ParameterValue=vpc-745bc04" "ParameterKey=EC2Subnets,ParameterValue=subnet-02aa2449,subnet-c70ac7e8"
parameters[3] ParameterKey, ParameterValue or UsePreviousValue expected
```

**Comment by michaelwittig** [comment]
the answer might be https://aws.amazon.com/de/premiumsupport/knowledge-center/multiple-values-list-parameter-cli/

Can you try:

```
sudo /usr/bin/cfn-create-or-update --stack-name sample --template-body file://Tomcat-app-cfn.yaml --region us-east-1 --parameters "ParameterKey=KeyName,ParameterValue=rg-newkey" "ParameterKey=AppURL,ParameterValue=http://localhost/app.war" "ParameterKey=VPCId,ParameterValue=vpc-12345" ParameterKey=EC2Subnets,ParameterValue=\"subnet-123456,subnet-789109\"
```

**Comment by stijnvanrenterghem** [comment]
The following command is working with aws cli
ParameterKey=RdsSubnetIds,ParameterValue=\"subnet-123456,subnet-3456789\"

but not with cfn-create-or-update
=> parameters[3] ParameterKey, ParameterValue or UsePreviousValue expected

**Comment by michaelwittig** [comment]
@stijnvanrenterghem can you add the output of `aws --version` ?

**Comment by michaelwittig** [comment]
In the new version 1.3.0, this works `ParameterKey=EC2Subnets,ParameterValue=\"subnet-123456,subnet-789109\"` which is also the only format that works for me in the AWS CLI on my Mac.
